---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/awysolution/public_html/.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/web_apiscc/
      - /bin/rsync -av ./ $DEPLOYPATH