---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/awysolution/public_html/citas.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_citas/
      - /bin/rsync -av ./ $DEPLOYPATH